### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by madskristensen** [Peter-Juhasz/IniLanguageService#1]
In an empty `.ini` file I get some exceptions as soon as I start typing:

```
System.NullReferenceException: Object reference not set to an instance of an object. at IniLanguageService.Syntax.IniSyntacticParser.Parse(ITextSnapshot snapshot) in C:\Users\bluec\Source\IniLanguageService\IniLanguageService\Syntax\IniSyntacticParser.cs:line 102 at IniLanguageService.Syntax.TextSnapshotExtensions.GetSyntaxTree(ITextSnapshot snapshot) in C:\Users\bluec\Source\IniLanguageService\IniLanguageService\Syntax\SyntaxTree.cs:line 59 at IniLanguageService.IniClassifierProvider.IniClassifier.GetClassificationSpans(SnapshotSpan span) in C:\Users\bluec\Source\IniLanguageService\IniLanguageService\Classification\IniClassifier.cs:line 100 at Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierTagger.<GetTags>d__5.MoveNext() at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<GetTagsForBuffer>d__38.MoveNext()
```

and

```
System.NullReferenceException: Object reference not set to an instance of an object. at IniLanguageService.Syntax.IniSyntacticParser.Parse(ITextSnapshot snapshot) in C:\Users\bluec\Source\IniLanguageService\IniLanguageService\Syntax\IniSyntacticParser.cs:line 102 at IniLanguageService.Syntax.TextSnapshotExtensions.GetSyntaxTree(ITextSnapshot snapshot) in C:\Users\bluec\Source\IniLanguageService\IniLanguageService\Syntax\SyntaxTree.cs:line 59 at IniLanguageService.IniHighlightSectionInQualifiedPropertyNamesTaggerProvider.IniHighlightSectionInQualifiedPropertyNamesTagger.<GetTags>d__6.MoveNext() in C:\Users\bluec\Source\IniLanguageService\IniLanguageService\ReferenceHighlighting\IniHighlightSectionInQualifiedPropertyNamesTagger.cs:line 53 at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<GetTagsForBuffer>d__38.MoveNext()
```

and

```
System.NullReferenceException: Object reference not set to an instance of an object. at IniLanguageService.Syntax.IniSyntacticParser.Parse(ITextSnapshot snapshot) in C:\Users\bluec\Source\IniLanguageService\IniLanguageService\Syntax\IniSyntacticParser.cs:line 102 at IniLanguageService.Syntax.TextSnapshotExtensions.GetSyntaxTree(ITextSnapshot snapshot) in C:\Users\bluec\Source\IniLanguageService\IniLanguageService\Syntax\SyntaxTree.cs:line 59 at IniLanguageService.IniErrorTaggerProvider.IniErrorTagger.GetTags(NormalizedSnapshotSpanCollection spans) in C:\Users\bluec\Source\IniLanguageService\IniLanguageService\Diagnostics\IniErrorTagger.cs:line 46 at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<GetTagsForBuffer>d__38.MoveNext()
```

**Comment by Peter-Juhasz** [comment]
Thanks for the report. I have implemented a quick fix and have been published the new version to the gallery.
However, I still have to work on the handling of syntax trees which are mostly incomplete.
